version: "2.3"

services:

  unprotected-server:
    image: approov/ruby:3.1
    build: ./
    networks:
      - default
    command: bash -c "rails server --port 8002 --binding 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/unprotected-server/hello:/home/developer/workspace
      - .local/bundle:/usr/local/bundle

  approov-token-check:
    image: approov/ruby:3.1
    build: ./
    networks:
      - default
    command: bash -c "rails server --port 8002 --binding 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-check/hello:/home/developer/workspace
      - .local/bundle:/usr/local/bundle

  approov-token-binding-check:
    image: approov/ruby:3.1
    build: ./
    networks:
      - default
    command: bash -c "rails server --port 8002 --binding 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-binding-check/hello:/home/developer/workspace
      - .local/bundle:/usr/local/bundle

